server:
  port: 8082
  servlet:
    context-path: /easyprice
spring:
  datasource:
    url: jdbc:mysql://111.231.232.212:3306/xiaochengxu?characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: mysqlroot
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  configuration:
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/*.xml



